name: Automated web scraper

on:
    schedule:
        - cron: '0 6 * * *'

jobs:
    web-scraping:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9

            - name: Install Dependencies
              run: pip install -r requirements.txt

            - name: Run Web Scraping Script
              run: python news_crawler_and_email.py
